version: 2.1
jobs:
  build:
    branches:
      only:
        - main
    docker:
      - image: andthensome/alpine-hugo-git-bash
    steps:
      - run:
          name: build site and push to github-pages
          command: sh publish.sh
