version: 2.1
 
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
      steps:
        - checkout
        - run: echo "this is the build job"
 
workflows:
  build_and_test:
    jobs:
      - build
