version: 2.1

parameters:
  pull_request:
    type: boolean
    default: false

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    resource_class: large
    steps:
      - checkout
      - run: echo "This is the building step!"
  deploy_prod:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run: echo "This is the production VM"
  deploy_stage:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run: echo "This is the staging VM"
 
workflows:
  build-deploy:
    when: << pipeline.parameters.pull_request >>
    jobs:
      - build:
          filters:
            branches:
              only: 
                - /dev.*/
                - /prod.*/
      - deploy_stage:
          requires: 
            - build
          filters:
            branches:
              only: /dev.*/
      - deploy_prod:
          requires: 
            - build
          filters:
            branches:
              only: /prod.*/
