version: 2.1

orbs: 
  aws-s3: circleci/aws-s3@3.0.0

parameters:
  pull_request:
    type: boolean
    default: false

jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - checkout
      - run: echo "This is the building step!"
  deploy_prod:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - run: echo "This is the production VM"
      - checkout
      - run: mkdir bucket && echo "This is test uploading to S3!" > bucket/build_asset.txt
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          to: 's3://awsbucketduyl/circleCI-test/'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: bucket/build_asset.txt
          to: 's3://awsbucketduyl'
  deploy_stage:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - run: echo "This is the staging VM"
workflows:
  version: 2
  build-deploy:
    when: << pipeline.parameters.pull_request >>
    jobs:
      - build:
          filters:
            branches:
              only: 
                - /dev.*/
                - /prod.*/
      - deploy_stage:
          requires: 
            - build
          filters:
            branches:
              only: /dev.*/
      - deploy_prod:
          requires: 
            - build
          filters:
            branches:
              only: /prod.*/
