version: 2

parameters:
  pull_request:
    type: boolean
    default: false

jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    resource_class: large
    steps:
      - checkout
      - run: echo "This is the building step!"
  deploy_prod:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run: echo "This is the production VM"
  deploy_stage:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - run: echo "This is the staging VM"
      - run: mkdir bucket && echo "This is test uploading to S3!" > bucket/build_asset.txt
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync bucket s3://awsbucketduyl97/circleCI-test/ 
workflows:
  build-deploy:
    when: << pipeline.parameters.pull_request >>
    jobs:
      - build:
          filters:
            branches:
              only: 
                - /dev.*/
                - /prod.*/
      - deploy_stage:
          requires: 
            - build
          filters:
            branches:
              only: /dev.*/
      - deploy_prod:
          requires: 
            - build
          filters:
            branches:
              only: /prod.*/
