on:
  pull_request:
    types: [closed]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.2
        with:
          GITHUB_REF: ${{ github.ref }}
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_TOKEN }}